spring:
  application:
    name: IMAGES-SERVICE
  datasource:
    password: 1234
    username: postgres
    url: jdbc:postgresql://localhost:5432/aphrinix_images_db
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    generate-ddl: true
    show-sql: true
server:
  port: 9004
  address: 192.168.121.1

eureka:
  client:
    service-url:
      defaultZone: http://192.168.121.1:9002/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true