
spring:
  main:
    allow-circular-references: true
  application:
    name: SHOP-AUTH-SERVICE
  data:
    mongodb:
      database: shop_authentication
      password: password
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/shop_authentication
      username: root
server:
  port: 8809

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true