
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aphrinix_images_db
    password: 1234
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  main:
    allow-circular-references: true
  application:
    name: SHOP-AUTH-SERVICE
server:
  port: 9001
  address: 172.26.128.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true